from setup.db.raw.config import db 

class INFO(db.Model):
    __tablename__ = "INFO"

    id = db.Column(db.Integer, primary_key = True)
    filename = db.Column(db.Text)
    filehash = db.Column(db.Text)
    load_level = db.Column(db.Integer)
    speed = db.Column(db.Text)
    type = db.Column(db.Text)
    game_type = db.Column(db.Text)
    real_type = db.Column(db.Float)
    category = db.Column(db.Text)
    is_ladder = db.Column(db.Boolean)
    is_private = db.Column(db.Boolean)
    map_hash = db.Column(db.Text)
    region = db.Column(db.Text)
    game_fps = db.Column(db.Float)
    frames = db.Column(db.Integer)
    build = db.Column(db.Integer)
    base_build = db.Column(db.Integer)
    release_string = db.Column(db.Text)
    amm = db.Column(db.Integer)
    competitive = db.Column(db.Integer)
    practice = db.Column(db.Integer)
    cooperative = db.Column(db.Integer)
    battle_net = db.Column(db.Integer)
    hero_duplicates_allowed = db.Column(db.Integer)
    map_name = db.Column(db.Text)
    expansion = db.Column(db.Text)
    windows_timestamp = db.Column(db.Integer)
    unix_timestamp = db.Column(db.Integer)
    end_time = db.Column(db.DateTime)
    time_zone = db.Column(db.Float)
    start_time = db.Column(db.DateTime)
    date = db.Column(db.DateTime)
    winner = db.Column(db.Integer, db.ForeignKey('PLAYER.id'))

